api:
  host: localhost
  port: 8000
  timeout: 300
  workers: 4
logging:
  file_rotation: 1 day
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  max_size: 100MB
model_settings:
  embedding:
    batch_size: 32
    device: cuda
    max_length: 512
    model_name: sentence-transformers/paraphrase-multilingual-mpnet-base-v2
  nlp:
    spacy_model: de_core_news_lg
    use_gpu: true
paths:
  data:
    external: /home/icl/Projekte/EngBot/data/external
    interim: /home/icl/Projekte/EngBot/data/interim
    processed: /home/icl/Projekte/EngBot/data/processed
    raw: /home/icl/Projekte/EngBot/data/raw
  models:
    checkpoints: /home/icl/Projekte/EngBot/models/checkpoints
    math: /home/icl/Projekte/EngBot/models/math
    nlp: /home/icl/Projekte/EngBot/models/nlp
  root: /home/icl/Projekte/EngBot
processing:
  pdf:
    allowed_extensions:
    - .pdf
    dpi: 300
    max_file_size_mb: 50
    ocr_language: deu
  text:
    encoding: utf-8
    max_length: 1000000
    min_length: 10
project:
  created_at: '2025-03-01 15:22:35'
  description: KI-gestütztes Normenmanagementsystem für Bauingenieurwesen
  environment: development
  name: NormenBot
  version: 2.0.0
system:
  cuda_available: true
  cuda_version: '12.4'
  gpu_devices:
  - NVIDIA RTX 3000 Ada Generation Laptop GPU
  os: Linux
  processor: x86_64
  python_version: 3.12.3
